[project]
name = "airport-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpy==1.24.4", "pydantic==2.8.2", "requests>=2.32.4"]
