name: datavalidator

on:
  pull_request:
    branches:
      - main
jobs:
  run-workflow-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Python & Dependencies
        uses: ./.github/actions/setup
        with:
          dev: false

      - name: Run TOML check
        run: uv run validate_data
