name: databuilder

on:
  push:
    branches:
      - main

jobs:
  run-workflow-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Python & Dependencies
        uses: ./.github/actions/setup
        with:
          dev: false

      - name: Run TOML check
        run: uv run combine_data

      - name: Archive generated files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: ./api

      - name: Checkout production branch
        uses: actions/checkout@v2
        with:
          ref: production

      - name: Download generated files artifact
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          path: ./api

      - name: Apply changes to production branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || (git commit -a -m "Add generated files from main branch" --allow-empty && git push origin production)
